ALTER TABLE plants
  ADD COLUMN IF NOT EXISTS category VARCHAR(50) NULL COMMENT '分类标签，如 Tropical/Temperate/Arid';

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS level INT DEFAULT 1 COMMENT '用户等级',
  ADD COLUMN IF NOT EXISTS points INT DEFAULT 0 COMMENT '积分',
  ADD COLUMN IF NOT EXISTS bio TEXT NULL COMMENT '个人简介';

CREATE TABLE IF NOT EXISTS user_achievements (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  name VARCHAR(100) NOT NULL COMMENT '成就名称',
  icon VARCHAR(20) NOT NULL COMMENT '图标 emoji',
  earned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_user (user_id),
  CONSTRAINT fk_user_achievements_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE plant_ecology
  ADD COLUMN IF NOT EXISTS light_tolerance INT DEFAULT 50,
  ADD COLUMN IF NOT EXISTS water_requirement INT DEFAULT 50,
  ADD COLUMN IF NOT EXISTS temperature_tolerance INT DEFAULT 50,
  ADD COLUMN IF NOT EXISTS air_humidity INT DEFAULT 50,
  ADD COLUMN IF NOT EXISTS drought_tolerance INT DEFAULT 50,
  ADD COLUMN IF NOT EXISTS cold_tolerance INT DEFAULT 50;
